add bap repair tool

diff --git a/build-a-pi b/build-a-pi
--- a/build-a-pi
+++ b/build-a-pi
@@ -560,6 +560,26 @@ EOF
 
 sudo mv build-a-pi.desktop /usr/share/applications/
 
+#create repair-bap tool
+cat <<EOF > /run/user/$UID/repair-bap
+#!/bin/bash
+
+if [ ! -f $HOME/pi-build/update ]; then
+echo "################################"
+echo "#  BAP update tool not found.  #"
+echo "#  Repairing, please stand by  #"
+echo "################################"
+cd $HOME
+git clone https://github.com/km4ack/pi-build.git || echo "Could not connect to Github. Check your internet and try again"
+echo "Repair complete. Run the Build a Pi update tool using the shortcut in the Pi menu"
+else
+clear;echo;echo
+echo "Update tool is present on the system."
+fi
+EOF
+chmod +x /run/user/$UID/repair-bap
+sudo mv /run/user/$UID/repair-bap /usr/local/bin/
+
 #####################################
 #	Install Base Apps
 #####################################
